version: 2
registries:
  takumi_guard_npm:
    type: npm-registry
    url: https://npm.flatt.tech/
    token: ${{secrets.TAKUMI_GUARD_TOKEN}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - takumi_guard_npm
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
